import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import clsx from 'clsx';
import Footer from "@/components/Footer";
import Form from "@/components/Form";
import Meeting from "@/components/Meeting";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function LocaleLayout(
    {
        children,
        params: {locale}
    }: {
        children: React.ReactNode;
        params: { locale: string };
    }) {
    return (
        <html lang={locale}>
        <body className={clsx(inter.className, 'antialiased text-gray-900 text-medium')}>
        <Navbar/>
        {children}
        <Form/>
        <Footer/>
        <Meeting/>
        </body>
        </html>
    );
}